functions ={
    "aba": "aba",
    "address": "address",
    "administrative_unit": "administrative_unit",
    "am_pm": "am_pm",
    "android_platform_token": "android_platform_token",
    "android_user_agent": "android_user_agent",
    "ascii_company_email": "ascii_company_email",
    "ascii_email": "ascii_email",
    "ascii_free_email": "ascii_free_email",
    "ascii_safe_email": "ascii_safe_email",
    "bank_country": "bank_country",
    "bban": "bban",
    "binary": "binary",
    "boolean": "boolean",
    "bothify": "bothify",
    "bs": "bs",
    "building_number": "building_number",
    "cache_pattern": "cache_pattern",
    "catch_phrase": "catch_phrase",
    "chrome": "chrome",
    "city": "city",
    "city_prefix": "city_prefix",
    "city_suffix": "city_suffix",
    "color": "color",
    "company": "company",
    "company_email": "company_email",
    "company_suffix": "company_suffix",
    "coordinate": "coordinate",
    "country": "country",
    "country_calling_code": "country_calling_code",
    "country_code": "country_code",
    "credit_card_expire": "credit_card_expire",
    "credit_card_full": "credit_card_full",
    "credit_card_number": "credit_card_number",
    "credit_card_provider": "credit_card_provider",
    "credit_card_security_code": "credit_card_security_code",
    "cryptocurrency": "cryptocurrency",
    "cryptocurrency_code": "cryptocurrency_code",
    "cryptocurrency_name": "cryptocurrency_name",
    "csv": "csv",
    "currency": "currency",
    "currency_code": "currency_code",
    "currency_name": "currency_name",
    "currency_symbol": "currency_symbol",
    "date": "date",
    "date_between": "date_between",
    "date_between_dates": "date_between_dates",
    "date_of_birth": "date_of_birth",
    "date_this_century": "date_this_century",
    "date_this_decade": "date_this_decade",
    "date_this_month": "date_this_month",
    "date_this_year": "date_this_year",
    "date_time": "date_time",
    "date_time_ad": "date_time_ad",
    "date_time_between": "date_time_between",
    "date_time_between_dates": "date_time_between_dates",
    "date_time_this_century": "date_time_this_century",
    "date_time_this_decade": "date_time_this_decade",
    "date_time_this_month": "date_time_this_month",
    "date_time_this_year": "date_time_this_year",
    "day_of_month": "day_of_month",
    "day_of_week": "day_of_week",
    "delimiters": "delimiters",
    "dga": "dga",
    "domain_name": "domain_name",
    "domain_word": "domain_word",
    "dsv": "dsv",
    "ean": "ean",
    "ean13": "ean13",
    "ean8": "ean8",
    "email": "email",
    "emoji": "emoji",
    "file_extension": "file_extension",
    "file_name": "file_name",
    "file_path": "file_path",
    "firefox": "firefox",
    "first_name": "first_name",
    "first_name_female": "first_name_female",
    "first_name_male": "first_name_male",
    "first_name_nonbinary": "first_name_nonbinary",
    "first_name_suffix": "first_name_suffix",
    "fixed_width": "fixed_width",
    "format": "format",
    "free_email": "free_email",
    "free_email_domain": "free_email_domain",
    "future_date": "future_date",
    "future_datetime": "future_datetime",
    "generator_attrs": "generator_attrs",
    "get_formatter": "get_formatter",
    "get_providers": "get_providers",
    "hex_color": "hex_color",
    "hexify": "hexify",
    "hostname": "hostname",
    "http_method": "http_method",
    "iana_id": "iana_id",
    "iban": "iban",
    "image": "image",
    "image_url": "image_url",
    "internet_explorer": "internet_explorer",
    "ios_platform_token": "ios_platform_token",
    "ipv4": "ipv4",
    "ipv4_network_class": "ipv4_network_class",
    "ipv4_private": "ipv4_private",
    "ipv4_public": "ipv4_public",
    "ipv6": "ipv6",
    "isbn10": "isbn10",
    "isbn13": "isbn13",
    "iso8601": "iso8601",
    "items": "items",
    "itin": "itin",
    "job": "job",
    "json": "json",
    "language_code": "language_code",
    "language_name": "language_name",
    "last_name": "last_name",
    "last_name_female": "last_name_female",
    "last_name_male": "last_name_male",
    "last_name_nonbinary": "last_name_nonbinary",
    "last_name_suffix": "last_name_suffix",
    "latitude": "latitude",
    "latlng": "latlng",
    "lexify": "lexify",
    "license_plate": "license_plate",
    "linux_platform_token": "linux_platform_token",
    "linux_processor": "linux_processor",
    "local_latlng": "local_latlng",
    "locale": "locale",
    "localized_ean": "localized_ean",
    "localized_ean13": "localized_ean13",
    "localized_ean8": "localized_ean8",
    "location_on_land": "location_on_land",
    "longitude": "longitude",
    "mac_address": "mac_address",
    "mac_platform_token": "mac_platform_token",
    "mac_processor": "mac_processor",
    "md5": "md5",
    "military_apo": "military_apo",
    "military_dpo": "military_dpo",
    "military_ship": "military_ship",
    "military_state": "military_state",
    "mime_type": "mime_type",
    "month": "month",
    "month_name": "month_name",
    "msisdn": "msisdn",
    "name": "name",
    "name_female": "name_female",
    "name_male": "name_male",
    "name_nonbinary": "name_nonbinary",
    "name_prefix": "name_prefix",
    "name_suffix": "name_suffix",
    "nic_handle": "nic_handle",
    "nic_handle_female": "nic_handle_female",
    "nic_handle_male": "nic_handle_male",
    "nic_handle_nonbinary": "nic_handle_nonbinary",
    "null_boolean": "null_boolean",
    "numerify": "numerify",
    "opera": "opera",
    "paragraph": "paragraph",
    "paragraphs": "paragraphs",
    "parse": "parse",
    "password": "password",
    "past_date": "past_date",
    "past_datetime": "past_datetime",
    "phone_number": "phone_number",
    "port_number": "port_number",
    "postalcode": "postalcode",
    "postalcode_in_state": "postalcode_in_state",
    "postalcode_plus4": "postalcode_plus4",
    "prefix": "prefix",
    "prefix_female": "prefix_female",
    "prefix_male": "prefix_male",
    "prefix_nonbinary": "prefix_nonbinary",
    "price": "price",
    "profile": "profile",
    "provider": "provider",
    "providers": "providers",
    "psv": "psv",
    "pybool": "pybool",
    "pydecimal": "pydecimal",
    "pydict": "pydict",
    "pyfloat": "pyfloat",
    "pyint": "pyint",
    "pyiterable": "pyiterable",
    "pylist": "pylist",
    "pyset": "pyset",
    "pystr": "pystr",
    "pystr_format": "pystr_format",
    "pystruct": "pystruct",
    "pytimezone": "pytimezone",
    "pytuple": "pytuple",
    "random_choices": "random_choices",
    "random_digit": "random_digit",
    "random_digit_not_null": "random_digit_not_null",
    "random_digit_not_null_or_empty": "random_digit_not_null_or_empty",
    "random_digit_or_empty": "random_digit_or_empty",
    "random_element": "random_element",
    "random_elements": "random_elements",
    "random_int": "random_int",
    "random_letter": "random_letter",
    "random_letters": "random_letters",
    "random_lowercase_letter": "random_lowercase_letter",
    "random_number": "random_number",
    "random_sample": "random_sample",
    "random_uppercase_letter": "random_uppercase_letter",
    "randomize_nb_elements": "randomize_nb_elements",
    "rgb_color": "rgb_color",
    "rgb_css_color": "rgb_css_color",
    "safari": "safari",
    "safe_color_name": "safe_color_name",
    "safe_email": "safe_email",
    "safe_hex_color": "safe_hex_color",
    "secondary_address": "secondary_address",
    "seed_instance": "seed_instance",
    "sentence": "sentence",
    "sentences": "sentences",
    "set_arguments": "set_arguments",
    "set_formatter": "set_formatter",
    "sha1": "sha1",
    "sha256": "sha256",
    "simple_profile": "simple_profile",
    "slug": "slug",
    "ssn": "ssn",
    "state": "state",
    "state_abbr": "state_abbr",
    "street_address": "street_address",
    "street_name": "street_name",
    "street_suffix": "street_suffix",
    "suffix": "suffix",
    "suffix_female": "suffix_female",
    "suffix_male": "suffix_male",
    "suffix_nonbinary": "suffix_nonbinary",
    "tar": "tar",
    "text": "text",
    "texts": "texts",
    "time": "time",
    "time_delta": "time_delta",
    "time_object": "time_object",
    "time_series": "time_series",
    "timezone": "timezone",
    "tld": "tld",
    "tsv": "tsv",
    "unique": "unique",
    "unix_device": "unix_device",
    "unix_partition": "unix_partition",
    "unix_time": "unix_time",
    "upc_a": "upc_a",
    "upc_e": "upc_e",
    "uri": "uri",
    "uri_extension": "uri_extension",
    "uri_page": "uri_page",
    "uri_path": "uri_path",
    "url": "url",
    "user_agent": "user_agent",
    "user_name": "user_name",
    "uuid4": "uuid4",
    "windows_platform_token": "windows_platform_token",
    "word": "word",
    "words": "words",
    "xml": "xml",
    "year": "year",
    "zipcode": "zipcode",
    "zipcode_in_state": "zipcode_in_state",
    "zipcode_plus4": "zipcode_plus4"
}

details ={
  "address": "Generates a random address.",
  "am_pm": "Generates a random AM or PM string.",
  "ascii_company_email": "Generates a random ASCII company email address.",
  "ascii_email": "Generates a random ASCII email address.",
  "ascii_free_email": "Generates a random ASCII free email address.",
  "ascii_safe_email": "Generates a random ASCII safe email address.",
  "bs": "Generates random corporate buzzwords.",
  "building_number": "Generates a random building number.",
  "catch_phrase": "Generates a random corporate catchphrase.",
  "century": "Generates a random century.",
  "chrome": "Generates a random user agent string for Google Chrome.",
  "city": "Generates a random city name.",
  "city_prefix": "Generates a random city prefix.",
  "city_suffix": "Generates a random city suffix.",
  "color": "Generates a random color name.",
  "company": "Generates a random company name.",
  "company_email": "Generates a random company email address.",
  "company_suffix": "Generates a random company suffix.",
  "country": "Generates a random country name.",
  "country_code": "Generates a random country code.",
  "credit_card_expire": "Generates a random credit card expiration date.",
  "credit_card_full": "Generates a full set of random credit card details.",
  "credit_card_number": "Generates a random credit card number.",
  "credit_card_provider": "Generates a random credit card provider.",
  "credit_card_security_code": "Generates a random credit card security code.",
  "cryptocurrency": "Generates a random cryptocurrency name and code.",
  "currency": "Generates a random currency name and code.",
  "currency_code": "Generates a random currency code.",
  "date": "Generates a random date.",
  "date_between": "Generates a random date between two given dates.",
  "date_this_century": "Generates a random date in this century.",
  "date_this_decade": "Generates a random date in this decade.",
  "date_this_month": "Generates a random date in this month.",
  "date_this_year": "Generates a random date in this year.",
  "day_of_month": "Generates a random day of the month.",
  "day_of_week": "Generates a random day of the week.",
  "domain_name": "Generates a random domain name.",
  "domain_word": "Generates a random domain word.",
  "email": "Generates a random email address.",
  "file_extension": "Generates a random file extension.",
  "file_name": "Generates a random file name.",
  "file_path": "Generates a random file path.",
  "firefox": "Generates a random user agent string for Mozilla Firefox.",
  "first_name": "Generates a random first name.",
  "first_name_female": "Generates a random first name for females.",
  "first_name_male": "Generates a random first name for males.",
  "free_email": "Generates a random free email address.",
  "free_email_domain": "Generates a random free email domain.",
  "future_date": "Generates a random date in the future.",
  "hex_color": "Generates a random hexadecimal color code.",
  "iban": "Generates a random International Bank Account Number (IBAN).",
  "image_url": "Generates a random image URL.",
  "internet_explorer": "Generates a random user agent string for Internet Explorer.",
  "ipv4": "Generates a random IPv4 address.",
  "ipv6": "Generates a random IPv6 address.",
  "isbn10": "Generates a random ISBN-10 code.",
  "isbn13": "Generates a random ISBN-13 code.",
  "iso8601": "Generates a random ISO 8601 formatted date string.",
  "job": "Generates a random job title.",
  "language_code": "Generates a random ISO 639-1 language code.",
  "last_name": "Generates a random last name.",
  "last_name_female": "Generates a random last name for females.",
  "last_name_male": "Generates a random last name for males.",
  "latitude": "Generates a random latitude.",
  "lexify": "Generates a random string, replacing ? characters with random letters.",
  "linux_platform_token": "Generates a random Linux platform token.",
  "locale": "Generates a random locale code.",
  "longitude": "Generates a random longitude.",
  "mac_address": "Generates a random MAC address.",
  "md5": "Generates a random MD5 hash.",
  "military_apo": "Generates a random military APO address.",
  "military_dpo": "Generates a random military DPO address.",
  "military_ship": "Generates a random military ship name.",
  "military_state": "Generates a random military state abbreviation.",
  "mime_type": "Generates a random MIME type.",
  "month": "Generates a random month name.",
  "month_name": "Generates a random month name.",
  "msisdn": "Generates a random MSISDN number.",
  "name": "Generates a random full name.",
  "name_female": "Generates a random full name for females.",
  "name_male": "Generates a random full name for males.",
  "null_boolean": "Generates a random boolean value, which could also be null.",
  "numerify": "Generates a random string, replacing # characters with random digits.",
  "opera": "Generates a random user agent string for Opera.",
  "paragraph": "Generates a random paragraph of text.",
  "paragraphs": "Generates a list of random paragraphs.",
  "password": "Generates a random password string.",
  "phone_number": "Generates a random phone number.",
  "postalcode": "Generates a random postal code.",
  "postcode": "Generates a random postcode.",
  "prefix": "Generates a random name prefix (e.g., Mr., Mrs.).",
  "prefix_female": "Generates a random name prefix for females.",
  "prefix_male": "Generates a random name prefix for males.",
  "profile": "Generates a random user profile.",
  "provider": "Generates a random provider name.",
  "random_digit": "Generates a random digit (0-9).",
  "random_digit_not_null": "Generates a random digit (1-9).",
  "random_digit_not_null_or_empty": "Generates a random digit or an empty string.",
  "random_element": "Generates a random element from a provided list.",
  "random_int": "Generates a random integer between two values.",
  "random_letter": "Generates a random letter.",
  "random_lowercase_letter": "Generates a random lowercase letter.",
  "random_number": "Generates a random number.",
  "randomize_nb_elements": "Generates a random number of elements.",
  "rgb_color": "Generates a random RGB color.",
  "rgb_css_color": "Generates a random RGB CSS color.",
  "safari": "Generates a random user agent string for Safari.",
  "safe_color_name": "Generates a random safe color name.",
  "safe_email": "Generates a random safe email address.",
  "secondary_address": "Generates a random secondary address.",
  "seed": "Sets the random seed for the Faker instance.",
  "sentence": "Generates a random sentence.",
  "sentences": "Generates a list of random sentences.",
  "sha1": "Generates a random SHA1 hash.",
  "sha256": "Generates a random SHA256 hash.",
  "slug": "Generates a random slug (e.g., for URLs).",
  "ssn": "Generates a random Social Security Number.",
  "state": "Generates a random state name.",
  "state_abbr": "Generates a random state abbreviation.",
  "street_address": "Generates a random street address.",
  "street_name": "Generates a random street name.",
  "street_suffix": "Generates a random street suffix.",
  "suffix": "Generates a random name suffix (e.g., Jr., Sr.).",
  "text": "Generates a random block of text.",
  "time": "Generates a random time.",
  "timezone": "Generates a random timezone.",
  "tld": "Generates a random top-level domain.",
  "unix_time": "Generates a random Unix timestamp.",
  "uri": "Generates a random URI.",
  "uri_extension": "Generates a random URI extension.",
  "uri_page": "Generates a random URI page.",
  "uri_path": "Generates a random URI path.",
  "url": "Generates a random URL.",
  "user_agent": "Generates a random user agent string.",
  "uuid4": "Generates a random UUID version 4.",
  "word": "Generates a random word.",
  "words": "Generates a list of random words.",
  "year": "Generates a random year.",
  "zipcode": "Generates a random ZIP code.",
  "zipcode_plus4": "Generates a random ZIP+4 code."
}
